import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cairo_Play } from "next/font/google"; // Import Cairo Play properly
import "./globals.css";

// Import Geist Sans and Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Import Cairo Play font
const cairoPlay = Cairo_Play({
  variable: "--font-cairo-play",
  subsets: ["latin"],
  weight: ["200", "400", "600", "800", "1000"], // Specify desired font weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairoPlay.variable} antialiased min-h-screen backgorundColor`}
      >
        {children}
      </body>
    </html>
  );
}
