import tokens from "./tokens";
import addresses from "../constants/addresses";
export interface ZapTokenType {
    symbol: string,
    decimals: number,
    lpAddresses: string,
    lpSymbol: string,
    isTokenOnly: string,
    logoA: string,
    logoB: string | undefined,
    tokenAAddress: string | undefined,
    tokenBAddress: string | undefined,
}
export const zapList = [
    {
      lpSymbol: tokens.snow.symbol,
      symbol: "TEST2",
      isTokenOnly: true,
      lpAddresses: tokens.snow.address,
      decimals: 18,
      logoA: tokens.snow.logo,
    },
    {
      lpSymbol: tokens.pls.symbol,
      symbol: "WPLS",
      isTokenOnly: true,
      lpAddresses: tokens.pls.address,
      decimals: 18,
      logoA: tokens.pls.logo,
    },
    {
      lpSymbol: tokens.wpls.symbol,
      symbol: "WPLS",
      isTokenOnly: true,
      lpAddresses: tokens.wpls.address,
      decimals: 18,
      logoA: tokens.wpls.logo,
    },
    {
      lpSymbol: tokens.dai.symbol,
      symbol: "DAI",
      isTokenOnly: true,
      lpAddresses: tokens.dai.address,
      decimals: 18,
      logoA: tokens.dai.logo,
    },
    {
      lpSymbol: tokens.bill.symbol,
      symbol: "TEST1",
      isTokenOnly: true,
      lpAddresses: tokens.bill.address,
      decimals: 18,
      logoA: tokens.bill.logo,
    },
    {
      lpSymbol: "SNOW-WPLS",
      symbol: "TEST2",
      isTokenOnly: false,
      lpAddresses: addresses.snowWplslp,
      decimals: 18,
      logoA: tokens.snow.logo,
      logoB: tokens.wpls.logo,
      tokenAAddress: tokens.snow.address,
      tokenBAddress: tokens.wpls.address,
    },
    {
      lpSymbol: "BILL-WPLS",
      symbol: "TEST1",
      isTokenOnly: false,
      lpAddresses: addresses.billWplslp,
      decimals: 18,
      logoA: tokens.snow.logo,
      logoB: tokens.wpls.logo,
      tokenAAddress: tokens.bill.address,
      tokenBAddress: tokens.wpls.address,
    },
  ];